### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Kr0nZ** [delta534/Chisel#1]
I tried updating my modpacks chisel mod with this new version, but got a crash. So I started up a clean instance with only the chisel mod and the required libraries, still got same crash.

```
java.lang.RuntimeException: No valid textures found for chisel block variation 'Grassy Dirt bricks in disarray' (Grass/bricks)
```

http://pastebin.com/vUEtcYUB

**Comment by delta534** [comment]
Fixed by f6ea10fde1
